package de.nerogar.noise.util;

import de.nerogar.noiseInterface.math.IVector3f;

public class Ray implements Cloneable {

	private IVector3f start;
	private IVector3f dir;

	public Ray(IVector3f start, IVector3f dir) {
		this.start = start;
		this.dir = dir;
	}

	public IVector3f getStart()           { return start; }

	public void setStart(IVector3f start) { this.start = start; }

	public IVector3f getDir()             { return dir; }

	public void setDir(IVector3f dir)     { this.dir = dir; }

	@Override
	public Ray clone() {
		return new Ray(start.clone(), dir.clone());
	}

	@Override
	public String toString() {
		return "Ray{" + "start: " + start + ", dir: " + dir + '}';
	}

	@Override
	public boolean equals(Object o) {
		// generated by IntelliJ IDEA
		if (this == o) return true;
		if (o == null || getClass() != o.getClass()) return false;

		Ray ray = (Ray) o;

		if (start != null ? !start.equals(ray.start) : ray.start != null) return false;
		return dir != null ? dir.equals(ray.dir) : ray.dir == null;
	}

	@Override
	public int hashCode() {
		// generated by IntelliJ IDEA
		int result = start != null ? start.hashCode() : 0;
		result = 31 * result + (dir != null ? dir.hashCode() : 0);
		return result;
	}
}
